site_name: Recherches Embedding
site_url: https://embedding-groupe.github.io/MKDocs/
nav :
  - Accueil: index.md
  - Recherches: recherches.md
theme :
  name: material

  palette:
    - scheme: default
      primary: purple
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Basculer en mode sombre
    - scheme: slate
      primary: purple
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Basculer en mode clair